intro:
title: Task-Agnostic Reinforcement Learning
description:
- Workshop at ICLR, 06 May 2019, New Orleans
- Building agents that explore and learn in the absence of rewards
buttons:
  Speakers: '#speakers'
  Dates: '#dates'
  Submissions: '#submissions'
  Schedule: '#schedule'
  Organizers: '#organizers'
